### ISSUE TITLE
关于论文的一点小问题

### ISSUE THREAD

**Issue by zhhao1** [Raincleared-Song/ConPET#1]
您好，关于论文我有个问题想问下。
conpet中的动态的方法，两个步骤。我理解的是第一个步骤是为了训练选择器，让模型能正确找到任务对应的pet模块，第二个步骤更新pet模块。
那直接用更简单的办法不也能达到效果吗。好比原来有k-1个任务，训练了k-1个pet模块，新来一个第k个任务，直接在原始的llama2上训一个关于第k个任务的pet模块（好比lora）。然后用个if else是不是也能解决，判断是执行第K个任务就用第k个pet，否则用前面的。可能不太优雅，但是我觉得这样是不是也能简单快捷的解决问题。
可能有理解不到位的地方，有错误希望您能指正。

**Comment by Raincleared-Song** [comment]
谢谢您的提问！在测试的时候，我们并不知道某个输入属于具体的哪个任务，因此才需要训练一个k-分类的选择器找到对应的pet模块，这也是我们论文中第一个步骤的目的，即您在提问中说的“用个if else判断是否执行第K个任务”也是需要由一个训练过的选择器来承担的，而不是已知的ground truth。
不知道是否正确理解并解答了您的问题，如果还有困惑的话欢迎追问！

**Comment by zhhao1** [comment]
> 谢谢您的提问！在测试的时候，我们并不知道某个输入属于具体的哪个任务，因此才需要训练一个k-分类的选择器找到对应的pet模块，这也是我们论文中第一个步骤的目的，即您在提问中说的“用个if else判断是否执行第K个任务”也是需要由一个训练过的选择器来承担的，而不是已知的ground truth。 不知道是否正确理解并解答了您的问题，如果还有困惑的话欢迎追问！

谢谢回复。那这样做您感觉怎么样，
先定义一个任务集，{A，B，C}
在TABLE I的输入模板里，多加一句，好比this task is A.
然后选择pet模块的时候用个判断，if task == 'A',就选择A对应的Pet。
这样可以保证不影响之前的pet模块，但是这样可能会限制一个任务只能用一个pet，并且没办法实现多个pet模块之间的交互。训练新的Pet模块的时候也没办法利用之前的已经学习好的pet模块，可能会导致性能有所下降？

**Comment by Raincleared-Song** [comment]
您好！有一点没有理解的是，this task is A 中的 "A" 是需要一个模块去推断填充的，还是已知的 ground truth 呢？选择 pet 模块的时候，if task == 'A' 这个判断又是哪个模块以什么方式来做？

**Comment by zhhao1** [comment]
您好。这里我意思是已知的ground truth任务。之前你提到说“在测试的时候，我们并不知道某个输入属于具体的哪个任务，”，但是在测试的时候应该是知道要执行什么任务的啊，就好比您表1里列举的两个。
如果已知ground truth任务的情况下，简单的判断现在的任务是什么，然后选择对应任务的Lora模块。
这里您说的并不知道输入属于具体哪个任务，我不太理解，给定输入需要执行什么任务，这个不应该是事先就定义好的吗，就好比在Table 1里所展示的。
我不是做这个领域的，只是最近在研究大模型lora相关的可持续性学习，有误解的地方希望您指正。

**Comment by Raincleared-Song** [comment]
您好，我理解您的困惑了，我们说的“任务”概念并不相同。一个输入是关系识别还是实体识别，这确实是已知的，但本文的持续学习说的任务，指的主要是不同的类别组（文中的用词是 schema）。
举个例子，我们在一个下游业务场景里面，需要持续训练一个模型做实体识别，但会不断有新的实体类别加入进来，这时已经存在的若干类别组就是“旧任务”，新加入的这些类别可以归为一组，即“新任务”。一段带实体的文本输入模型，我们在测试的时候并不知道它属于哪一个类别组，即不知道它属于哪一个“任务”。所以，我们需要选择器。

**Comment by zhhao1** [comment]
不好意思回复这么晚，非常感谢详细的回答，是我之前的理解有问题。

**Comment by Raincleared-Song** [comment]
好的，那没问题我就先关 issue 了
